### ISSUE TITLE
Remover menu de contexto

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#123]
Necessário remover o menu de contexto da versão de homologação

**Tasks**
- [x] Atualizar as `stories` para não chegar mais no menu de contexto
- [x] Testar bot para verificar se o comportamento está correto mesmo sem o menu
- [x] Subir pro ambiente de beta (quarta-feira de manhã)
- [x] Colocar o aviso de "Manutenção" na página web
- [x] Subir pro ambiente de produção (fim de semana)
- [x] Avisar aos beta testers
- [x] Atualizar CHANGELOG

-------

**Critérios de aceitação**
- [x] Bot atualizado e funcionando sem menu
- [x] Versão sem menu publicada em ambiente de **dev**.
- [x] Versão sem menu publicada em ambiente de **beta**.
- [x] Versão sem menu publicada em ambiente de **prod**.
- [ ] Página web com aviso de manutenção
- [x] Beta testers avisados por e-mail sobre a manutenção e atualização

**Comment by rodmaia** [comment]
Atualizei o conteúdo do changelog na branch `maintenance_page`.
Também criei a mensagem de manutenção em `manutencao.html`, mas precisa carregar esse conteúdo no template do django e criar a lógica pra ficar fácil de trocar a index pela página de manutenção. 
Aliás, poderia até integrar a msg de manutenção em `home.html` e criar uma variável no Django pra carregar esse bloco.

**Comment by rodmaia** [comment]
@RochaCarla vamos ter algum protocolo pra subir as versões em prod? Precisamos ter a aprovação do MinC ou podemos subir direto?

**Comment by RochaCarla** [comment]
Podemos subir direto

**Comment by MatheusMiranda** [comment]
Para ativar/desativar a página de manutenção bastar criar um objeto do tipo 'Maintainance' no django admin, e marcar/desmarcar o atributo 'Set maintainance page'.

**Comment by rodmaia** [comment]
Falta (mapeado em #170):
* Mostrar msg de manutenção antes do login
* Subir para Beta
