### ISSUE TITLE
Melhorar broker do tracker

### ISSUE THREAD

**Issue by KahCosta** [lablivre-unb/tais#306]
Atualmente as mensagens estão sendo todas armazenadas em memória usando tracker store in memory. Esta solução não é escalavél. É necessário implementar o broker com interação com kafka.

**Tarefas**

- [X] Verificar quais as integrações já existem do broker
- [X] Criar issue da integração do broker com kafka no Rasa
- [ ] ~~Implementar e validar integração com o elastic.~~
- [X] Documentar o broker na página de documentação do Rasa.
- [ ] ~~Atualizar Docker compose com serviço do kafka~~

**Critérios de aceitação**

- [X] Abrir PR para o Rasa
- [ ] ~~Ter Elastic testado e atualizado~~
- [ ] ~~Readme atualizado para que qualquer pessoa do time seja capaz de subir a stack.~~

**Comment by MatheusMiranda** [comment]
Pull Request link: https://github.com/RasaHQ/rasa_core/pull/1648
