### ISSUE TITLE
Documentar o Roadmap do projeto no GH Pages

### ISSUE THREAD

**Issue by gabibguedes** [lablivre-unb/tais#431]
**Tarefas**

- [ ] Criar documento do roadmap no github pages
- [ ] Adicionar documento na SideBar

**Critérios de aceitação**

- [ ] Documentação no pages
- [ ] O roadmap pode ser compreendido pelos membros da equipe e por pessoas que não fazem parte da equipe
