### ISSUE TITLE
Melhorar Estrutura do Repositório

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#482]
Mesmo com melhorias no projeto, ainda existem atividades para melhorar o repositório. O objetivo é diminuir a barreira inicial de pessoas que queiram contruir um projeto Rasa. 

Além disso, a diagramação de todo o GH pages do projeto deve ser feito para melhorar o entendimento do projeto.

**Tarefas**

- [x] Refatorar `labels`
- [x] ~Refatorar `milestones`~
- [x] ~Refatorar `releases`~
- [ ] Refatorar `issues`
- [x] ~Criar template de PR~
- [x] Atualizar `code of conduct`
- [x] Descrever a documentação da Arquitetura
- [x] Criar tutoriais de criação da primeira conversa
- [x] ~Criar tuturiais sobre a estrutura do projeto~
- [x] #432 
- [ ] #431 
- [ ] #430 
- [x] #428
- [ ] #427 
- [ ] #426 
- [ ] #424 
- [ ] #422 
- [ ] #420 
- [x] #418 
- [x] #488 

**Critérios de aceitação**

- [ ] Documentar cada mudança feita nesta issue
- [ ] Projeto com todas as configurações de um bom projeto FLOSS

**Comment by arthurTemporim** [comment]
Exemplos de páginas de comunidades:
https://rasa.com/
https://reactjs.org/
https://github.com/collections/github-pages-examples

**Comment by LeoSilvaGomes-zz** [comment]
### Tópico:
 - Refatorar `labels`

### Resolução:
A partir da analise feita das Labels do repositório, percebeu-se a conduta de cada `labels` e seu vies dentro do repositório, e percebemos a necessidade de criação de mais Labels, onde determinamos parâmetros para a criação dos mesmos.
Ao criar um issue tem se necessidade de especificar, do que a issue se trata, qual será o trabalho dentro da mesma e as habilidade necessárias para executa-la.

Desta forma, tivemos a caráter de criação de tais `labels`: 

- O que é?
Tais
Boiler-Plate
Devops
RoaunetBot
HelpWanted
GoodFirstIssue
PlataformaConteudo
Epic
Production 
Enhancement
Maintenance
Burocracia
Github-Pages

- Que tipo de trabalho?
Documentação
Bug
Beta
Conteúdo
Duvida
Ideia
DevOps
Dev
Teste

- Que habilidade técnica?
Python
Testes
Docker
Mark-Down
Jekyll
Rasa
ElasticShearch
RocketChat

**Comment by LeoSilvaGomes-zz** [comment]
### Tópico:
 -  Criar template de PR

### Resolução:

Analisando boa parte dos PR criados no repositório, notou-se um padrão muito comum entre eles.
Decidiu concluir o template bem simples e que agrega todas as issues:


### Template

[REVIEW/WIP] Nome do PR

Breve comentário sobre o contexto e descrição dp pull request.

Issues closes:
- [ ]
