### ISSUE TITLE
Planejar Beta Test

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#53]
* [x] Criar o ambiente
* [x] Comunicação com os testers
* [x] Criação do processo do teste
* [ ] Pensar no monitoramento
* [ ] Recolher o feedback

**Comment by brunapinos** [comment]
* Comunicação via lista de discussão 
* Primeiro contato via Whatsapp
* Login do ambiente de teste

**Comment by MatheusFaria** [comment]
- Mudar URLS para "tais"
- Página com changelog (página de fundo)

**Comment by rodmaia** [comment]
Monitoramento mapeado na épica #129 
Feedback do beta mapeado em #133
