### ISSUE TITLE
[Fallbecks] Estruturar os dados do tracker para a comunicação dos bots

### ISSUE THREAD

**Issue by guilacerda** [lablivre-unb/tais#552]
**Descrição da nova feature:**

É necessário fazer um filtro nos dados que recebemos do tracker quando efetuada uma requisição na API de cada bot, quando um está se comunicando com o outro.

**Tarefas**

- [x] Analisar e escolher quais dados são relevantes para a comunicação
- [x] Fazer um filtro nos dados que recebemos da requisição

**Critérios de aceitação**

- [x] Através dos dados o main bot escolhe a melhor opção de resposta

**Comment by guilacerda** [comment]
Os dados escolhidos foram:

* Intent name
* Confidence
* Messages (text - utter é um conjunto de mensagens)
* Bot name

Foram escolhidos esses dados porque são os necessários para que o bot principal escolha a melhor resposta dentre as que ele recebeu. Através da confiança de cada intent_name recebida, ele escolhe a melhor e faz uma busca pela mensagem correspondente daquela intent.

**Comment by joaovitor3** [comment]
Foi trabalhado nesse [Pull Request](https://github.com/lappis-unb/rasa-ptbr-boilerplate/pull/48)
